version: 2.1

windows-cpu: &windows_cpu
  machine:
    resource_class: windows.medium
    image: windows-server-2019-vs2019:stable
    shell: powershell.exe

jobs:
  test:
    <<: *windows_cpu
    steps:
      - checkout
      - run: ls
      - run: echo 'hello'

workflows:
    build:
        jobs:
            - test
