version: 2.1

jobs:
  Build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sleep 65
  Jest:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo sleep 300
  Lint check:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sleep 90
  Cypress E2E:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sleep 110
  Deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sleep 120

workflows:
  basic-workflow:
    jobs:
      - Build
      - Jest:
          requires:
            - Build
      - Lint check:
          requires:
            - Build
      - Cypress E2E:
          requires:
            - Build
      - Deploy:
          requires:
            - Jest
            - Lint check
            - Cypress E2E
