version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: python some_code.py

workflows:
  test:
    jobs:
      - build:
          context: sf-demo