version: 2.1

jobs:
  job_a:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sleep 65
  job_b:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sleep 65

workflows:
  basic-workflow:
    jobs:
      - job_a
      - job_b:
          requires:
            - job_a