version: 2.1

parameters:
  context-to-use:
    type: string
    default: 'sf-demo'

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo $GH_TOKEN

workflows:
  test:
    jobs:
      - build:
          context: << pipeline.parameters.context-to-use >>