version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - setup_remote_docker
      - checkout
      - run: ssh -G remote-docker | awk '/^hostname / { print $2 }'
      - run: ls
      - run: openssl version
      - run: echo 'hello'

workflows:
    build:
        jobs:
            - test
