version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          command: |
            while true; do
              sleep 1
              netstat -nputw
              echo "======"
            done
          background: true
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com
      - run: curl google.com

workflows:
    build:
        jobs:
            - test
